# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"C\n\x0eMessageRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\"!\n\x0eMessageRespone\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x19\n\x06UserID\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"=\n\x13UserIDsListRespones\x12&\n\x0buserIDsList\x18\x01 \x03(\x0b\x32\x11.chat.UserIDsList\"\"\n\x0bUserIDsList\x12\x13\n\x0buserIDsList\x18\x01 \x03(\t2\x96\x01\n\x13RealTimeChatSetvice\x12\x39\n\x0bSendMessage\x12\x14.chat.MessageRequest\x1a\x14.chat.MessageRespone\x12\x44\n\x19GetUserFollowingFollowers\x12\x0c.chat.UserID\x1a\x19.chat.UserIDsListResponesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=20
  _globals['_MESSAGEREQUEST']._serialized_end=87
  _globals['_MESSAGERESPONE']._serialized_start=89
  _globals['_MESSAGERESPONE']._serialized_end=122
  _globals['_USERID']._serialized_start=124
  _globals['_USERID']._serialized_end=149
  _globals['_USERIDSLISTRESPONES']._serialized_start=151
  _globals['_USERIDSLISTRESPONES']._serialized_end=212
  _globals['_USERIDSLIST']._serialized_start=214
  _globals['_USERIDSLIST']._serialized_end=248
  _globals['_REALTIMECHATSETVICE']._serialized_start=251
  _globals['_REALTIMECHATSETVICE']._serialized_end=401
# @@protoc_insertion_point(module_scope)
